/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.srsoftwares.studrecmgmt.gui;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author - Sumit Roy
 * @Created On - May 8, 2013 , 11:17:35 AM
 * @Project - Student Records Management
 */
public class ProgressPanel extends JPanel {

    /**
     * Creates new form ProgressPanel
     */
    public ProgressPanel() {
        initComponents();
     }

    public void setProgressLabelText(String progressLabelText) {
        progressLabel.setText(progressLabelText);
        progressLabel.updateUI();
    }
    
    public void setPanelBackgroundColor(Color backColor){
        this.setBackground(backColor);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataLoadingProgressBar = new javax.swing.JProgressBar();
        progressLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        dataLoadingProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        dataLoadingProgressBar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataLoadingProgressBar.setBorderPainted(false);
        dataLoadingProgressBar.setIndeterminate(true);
        dataLoadingProgressBar.setString("");

        progressLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressLabel.setText("Pleae Wait Wait While Data is being fetched");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataLoadingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataLoadingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar dataLoadingProgressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
}
